In [1]:
import pandas as pd
import numpy as np
import scipy.stats as stats
import statsmodels.formula.api as smf

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/ryupepa/Econometrica/master/python-notebooks/data-csv/sleep75.csv')
df

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,spwrk75,totwrk,union,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq
0,32,0,1,0.000000,0.000000,12,0,0,1,3529,...,0,3438,0,3438,0,14,0,13,7.070004,1024
1,31,0,2,0.000000,0.000000,14,9500,1,1,2140,...,0,5020,0,5020,0,11,0,0,1.429999,961
2,44,0,3,0.000000,0.000000,17,42500,1,1,4595,...,1,2815,0,2815,0,21,0,0,20.529997,1936
3,30,0,4,0.000000,0.000000,12,42500,1,1,3211,...,1,3786,0,3786,0,12,0,12,9.619998,900
4,64,0,5,0.000000,0.000000,14,2500,1,1,4052,...,1,2580,0,2580,0,44,0,33,2.750000,4096
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,45,0,702,0.182331,0.030075,12,5500,1,0,5069,...,1,2026,0,2026,0,27,0,18,NaN,2025
702,34,0,703,0.182331,0.030075,10,2500,0,0,5885,...,0,675,1,465,210,18,0,4,NaN,1156
703,37,0,704,0.182331,0.030075,12,3500,1,0,4719,...,1,1851,0,1851,0,19,0,17,NaN,1369
704,54,0,705,0.182331,0.030075,17,32500,1,0,5149,...,1,1961,1,1481,480,31,0,22,NaN,2916
705,30,0,706,0.182331,0.030075,16,6750,1,0,4747,...,0,2363,0,2363,0,8,1,9,NaN,900

In [3]:
model = smf.ols(data=df, formula='sleep~totwrk+south+totwrk*south+age+age*age+male+smsa').fit()
hat_output = model.predict()
model.predict()

array([3055.99241822, 3049.69286894, 3144.92641535, 2897.17815382,
       3301.87964692, 3479.88820925, 3300.7137148 , 3012.4101499 ,
       3249.24206639, 3097.79692731, 2557.75046582, 3428.31465956,
       3153.90610588, 3235.21887941, 3164.40794908, 3116.73468495,
       3117.258472  , 2968.47720153, 3262.82875426, 3374.39107906,
       3033.54664284, 3051.18400206, 3283.06747157, 3130.51058812,
       2786.93586802, 3090.35215423, 2990.99161319, 3128.36807277,
       3210.11421468, 3181.7182832 , 2980.18773719, 3006.00872377,
       3129.31744269, 3193.90395867, 3065.73485684, 2966.41239527,
       3174.672491  , 3459.1107191 , 3110.43553256, 3147.6113955 ,
       3116.37902565, 3142.90579032, 3164.98627235, 3302.61916867,
       3160.70349177, 3240.32988963, 3273.96872983, 3460.92039062,
       3327.82231017, 2743.94987978, 3023.75667949, 3089.18900436,
       3223.7767391 , 3128.37326482, 3170.17277065, 3233.45479466,
       3292.02758529, 3268.67549622, 3225.37751057, 3222.04538209,
       3036.94109305, 3191.6991216 , 3247.16115184, 3267.07205962,
       3349.03131732, 3481.12831816, 3196.85089106, 2879.11762154,
       3133.47464099, 3488.07906088, 3088.17897247, 3163.23357526,
       3193.20318384, 3441.64340482, 3126.64059652, 3215.20844683,
       3239.86751459, 3236.09910155, 3352.87233731, 3247.81094319,
       3316.98088962, 3682.87751377, 3360.36963966, 3131.15329444,
       3182.9241934 , 3166.77979141, 3432.03190157, 2942.53617317,
       3229.70468516, 3401.57159918, 3175.90427714, 3258.32124839,
       3252.55920908, 3292.87908371, 3275.53043128, 3339.24416392,
       3328.02599886, 3212.85637988, 3105.56348337, 2942.65565369,
       3202.57273238, 3137.21070354, 3081.34771026, 3156.98685701,
       3369.48921148, 3152.04785531, 3129.42803919, 3471.81830909,
       3416.44026332, 3160.30252874, 3389.69023341, 3042.33414703,
       3073.38027263, 3360.55413634, 3418.60773094, 3102.18383016,
       3121.5934081 , 2835.85181054, 3174.60497723, 3159.59618941,
       3319.75374617, 3394.22160907, 3398.1936296 , 3103.78738388,
       3058.67351761, 3334.89903251, 3253.09075765, 3390.14189143,
       3416.2530954 , 2948.11325041, 3185.17711646, 3223.86456282,
       3050.76693074, 3308.54465768, 2987.47693243, 2945.79171507,
       3372.5485643 , 3509.46486985, 3485.71757354, 3222.83832347,
       3325.30111367, 3344.77371642, 3306.04147602, 3240.87588673,
       3200.98084493, 3198.74057429, 3152.76936921, 3219.48488572,
       3200.60019333, 2853.84003858, 3022.61809428, 3151.80242004,
       3205.48112653, 3298.44802697, 3496.68976608, 3032.73026825,
       3666.665598  , 2973.64740276, 3125.74172238, 3175.87007844,
       3323.47193472, 3278.99092429, 3161.96581073, 3426.8017133 ,
       3449.34335136, 3033.96981591, 3164.99868866, 3029.99701333,
       3254.29647907, 3159.99993469, 3159.12195931, 3310.99066811,
       3063.16194416, 3127.06285988, 3461.54876392, 3303.66116191,
       3098.84484988, 3181.98667854, 3148.01235853, 3235.23664745,
       3292.64734694, 3359.34903737, 3330.450316  , 3234.50865932,
       3253.40445673, 3292.11523712, 2970.74047957, 3375.01074552,
       3270.36745431, 3293.22419924, 3341.97964137, 3371.2570499 ,
       3211.89365768, 3470.9188737 , 3213.65298539, 3291.60209356,
       3221.37124391, 3345.59675402, 3341.86532226, 3175.67733085,
       3383.27751348, 3525.71376658, 3289.77481125, 3122.55128447,
       3362.44527434, 3206.20245165, 3307.39793065, 3190.03230732,
       3112.55712004, 3221.74704126, 3311.29176701, 3328.74213193,
       3019.47759089, 3292.39894064, 3329.23474375, 3282.6703893 ,
       3166.18551954, 3282.89878458, 3191.82007309, 3206.59878389,
       3141.72356113, 3169.56073074, 3414.9680676 , 3299.12812437,
       3157.99300815, 3195.92479022, 3110.60920082, 3375.22168939,
       3203.11872948, 3221.69582455, 3171.8136538 , 3300.345588  ,
       3247.64129492, 3207.56926534, 3125.16061686, 3261.16266122,
       3058.94611611, 3208.27226117, 3257.66890802, 2979.44364078,
       3276.72523646, 3022.13738995, 3287.12314617, 3128.18273824,
       3162.96307785, 3384.03118225, 3270.0632005 , 3229.70468516,
       3383.54229143, 3215.64729947, 3244.8373955 , 3309.57226506,
       3088.16786745, 3259.58337856, 3469.2785518 , 3177.81077339,
       3315.3866819 , 3247.46374589, 3438.52188301, 2889.45023848,
       3148.86038843, 3136.19826185, 3214.74730283, 3230.95902981,
       3325.69279725, 3325.77807906, 3217.46926394, 3187.86134657,
       3660.8488097 , 3349.36197762, 3184.040191  , 3542.88061677,
       3326.58742252, 3284.73409706, 3201.02317762, 3197.40290362,
       3327.65896349, 3241.82450661, 3262.36359697, 3324.14704914,
       3454.83829351, 3255.18277722, 3357.65406495, 3345.7064408 ,
       3157.03882376, 3412.51315825, 3287.86498809, 2973.71713754,
       3389.8236012 , 3168.67815367, 3289.80424556, 3467.19041299,
       3332.18944294, 3400.27109109, 3302.18446198, 3289.90817905,
       3087.40270957, 3245.82697974, 3382.88312182, 3374.45358957,
       3283.9608052 , 3274.12373557, 3539.23071023, 3074.87877037,
       3706.144667  , 3069.00613456, 3523.81393335, 3181.80634726,
       3364.42683638, 3350.59289834, 3050.94726202, 3123.62069615,
       3171.17613953, 3377.40284545, 3134.30731264, 3271.12273133,
       3381.09841874, 3440.09138942, 3612.22117238, 3227.73824787,
       3048.63404946, 3309.30831172, 3277.2170458 , 3126.92764355,
       3209.1108458 , 3288.00406349, 3249.18565763, 3189.39923506,
       3165.83283128, 3394.62929063, 3241.15793049, 3211.06783782,
       3271.55393672, 3023.34330015, 3200.38566334, 3319.75818818,
       3120.89485428, 3246.16722823, 3519.15133606, 3552.66704783,
       3324.39466497, 3416.0859136 , 3119.14885996, 3211.47305407,
       3208.52010623, 3235.46672447, 3349.38312355, 3220.56687339,
       3151.19382231, 3113.47210246, 3250.19049748, 2955.72577878,
       3398.81424385, 3412.90745211, 3252.90052918, 3489.78956427,
       2911.31102758, 3156.25961892, 3393.12680505, 3307.77061202,
       3165.5317082 , 3263.79070017, 3168.02822308, 3382.68955616,
       3145.11932262, 3267.29408712, 3286.14773462, 3331.87634988,
       3267.69078248, 3093.44754268, 3201.46079922, 3241.26695257,
       3419.62089356, 3511.84626141, 3366.08425227, 3140.72297451,
       3441.88467791, 3346.73070843, 3282.37426947, 3402.94159949,
       3517.48261447, 3565.68686592, 3182.79507883, 3160.30565947,
       3137.09047298, 3236.69719932, 3153.12706073, 3342.22154281,
       3172.70661497, 3355.04326159, 3109.4364169 , 3194.0278812 ,
       3262.95320937, 3223.74933701, 3220.91956165, 3135.32178654,
       3322.76505123, 3380.99343859, 3302.48214492, 3046.36260833,
       3609.31277823, 3230.59143678, 3278.56482973, 3108.29968023,
       3434.67855609, 3299.05578454, 3205.52364889, 3540.6950187 ,
       3155.72732032, 3053.8051604 , 3367.81570498, 3216.64713606,
       3295.96114613, 3425.61314772, 3217.49072395, 3410.40804042,
       3209.34592608, 3174.09044666, 3186.25112983, 3253.11277891,
       3043.35825499, 3136.97099246, 3253.26367588, 3380.84495785,
       3332.06612643, 3099.69973158, 3079.03818967, 3529.02887706,
       3082.59595315, 3089.1840011 , 3567.78942693, 3462.06455956,
       3385.22332637, 3213.72319488, 3318.05717519, 3126.23018823,
       3213.62148239, 3331.50509964, 3216.95195112, 3323.92890129,
       3392.08928903, 3182.93510963, 3261.00012678, 3262.59070294,
       3755.58736761, 3176.85937125, 3194.27850851, 3177.58069637,
       3146.35943153, 3192.54659025, 3243.36367728, 3282.92321614,
       3163.08847134, 3150.45374685, 3417.03064048, 3202.79317534,
       3236.82778486, 3285.57878345, 3345.41995503, 3158.81604575,
       3224.37224815, 3170.2759541 , 3426.14790196, 3405.84999364,
       3575.65049754, 3163.45745666, 3169.80413379, 3549.47495016,
       3243.29006175, 3243.05498147, 3143.02952406, 3192.72451174,
       3580.33054918, 3349.92114635, 3385.85690038, 3171.82197657,
       3565.61343917, 3098.03366734, 3373.57899654, 3378.03873939,
       3266.22320447, 3435.43907055, 3204.77534845, 3328.62487242,
       3073.14278256, 3497.10420453, 3573.93412631, 3230.67907651,
       3303.62357992, 3444.20011148, 3131.14532014, 3486.49364766,
       3761.40415592, 3594.87251995, 3235.34871492, 3471.93268629,
       3197.05334608, 3306.07091032, 3319.35869612, 3395.68735299,
       3500.03224955, 3577.42215502, 3371.0062338 , 3269.89378546,
       3545.89719763, 3283.86500569, 3310.94113829, 3484.69033487,
       3658.75547884, 3517.48261447, 3541.68717423, 3410.66341307,
       3414.47346362, 3406.62606776, 3394.69013164, 3279.99132213,
       3409.53446191, 3406.62606776, 3490.76329099, 3451.52540404,
       3467.05808944, 3438.92431701, 3491.40599731, 3360.79919914,
       3384.48786569, 3490.51988795, 3460.42647577, 3209.73766729,
       3505.84903785, 3551.14489516, 3664.57226715, 3597.67920162,
       3239.02892996, 3469.0871155 , 3392.18599826, 3277.80703534,
       2976.25320286, 3067.91914362, 3701.74387687, 3565.68686592,
       3082.16796561, 3504.22624513, 3367.39755076, 3204.52731461,
       3126.29235027, 3564.01692093, 3236.23779532, 3087.40289836,
       3235.82219498, 3106.64528226, 3308.41331834, 3004.04728975,
       3270.73237009, 2930.54340497, 3120.89263328, 3224.42610843,
       3723.28576384, 3045.36499274, 3371.3698674 , 3098.84707089,
       3554.05328931, 3408.61096727, 3508.75743201, 3253.68816024,
       3440.41893399, 3222.16930462, 3268.00505725, 3459.17970385,
       3264.67014652, 3239.32633197, 3117.08924574, 3466.00949509,
       3475.60968189, 3504.27301983, 3334.33367411, 3171.17613953,
       3664.2776474 , 3328.08775934, 3206.02712363, 3409.89678422,
       2989.50513019, 3088.64447823, 3241.46662631, 3482.08619452,
       3284.79807854, 3107.23176862, 3317.87684392, 3192.25622372,
       3180.37036004, 3344.18575909, 3702.92700476, 3328.33172363,
       3292.62604662, 3242.06833752, 3255.23752622, 3258.01755584,
       3145.63441445, 3433.25258997, 3299.75452147, 3130.38813656,
       3229.28408156, 3322.98445274, 3557.19398149, 3335.3322121 ,
       3250.06344423, 2827.05764334, 3255.48537127, 3368.31019449,
       3324.33542883, 3579.2804056 , 3249.41573465, 3286.99756389,
       3390.66531655, 3566.08025622, 3415.22751648, 3340.31043851,
       3527.31306708, 3082.6011452 , 3348.50709592, 3070.71619124,
       2998.3403479 , 3581.46728585, 3625.80360704, 3076.83723335,
       3082.52862817, 3412.91042315, 3429.48891445, 3416.66406495,
       3227.26623878, 3479.54513891, 3257.32288277, 3148.12795829,
       3531.6500354 , 3646.35880567, 3174.19234792, 3068.38743164,
       3172.99754274, 3588.13895585, 3112.28693133, 3243.24328705,
       3236.47009334, 3122.18636869, 3269.47690294, 3387.99219146,
       3095.06220142, 3556.96168346, 3214.43860702, 3291.8601678 ,
       3145.70580898, 3293.45427626, 3273.00655627, 3338.41593427,
       3234.27025953, 2941.17583371, 3523.45327079, 3208.62460096,
       3031.82805061, 3321.96449622, 3022.87557338, 3081.47310376,
       3514.57422032, 3360.81033406, 3245.90993791, 3506.49693622,
       3196.38842972, 3114.10833455, 3475.42137631, 3234.9932444 ,
       3224.47863643, 3266.09336897, 3323.07921164, 3347.79846037,
       3184.3958503 , 3168.13140654, 3176.81259655, 3205.54698055,
       3132.23009007, 3077.41761794, 3220.33679638, 3044.47832213,
       3265.73714842, 3492.87971554, 3168.55645215, 3385.67675789,
       3337.88013248, 3551.14489516, 3200.0908548 , 3459.46841062,
       3265.37870686, 3204.78632973, 3168.56402488, 3301.07437736,
       3257.06559245, 3231.08573459, 3255.64515226, 3228.93971606,
       3182.68448233, 3353.31246583, 3334.01143019, 3267.32847462,
       3205.97747042, 3197.34871587, 3553.92789582, 3262.18029465,
       3375.77605775, 3259.95220514])

In [4]:
df['slp2'] =model.predict()**2
df['slp3'] =model.predict()**3
df['slp4'] =model.predict()**4
df

,age,black,case,clerical,construc,educ,earns74,gdhlth,inlf,leis1,...,worknrm,workscnd,exper,yngkid,yrsmarr,hrwage,agesq,slp2,slp3,slp4
0,32,0,1,0.000000,0.000000,12,0,0,1,3529,...,3438,0,14,0,13,7.070004,1024,9.339090e+06,2.854019e+10,8.721860e+13
1,31,0,2,0.000000,0.000000,14,9500,1,1,2140,...,5020,0,11,0,0,1.429999,961,9.300627e+06,2.836405e+10,8.650166e+13
2,44,0,3,0.000000,0.000000,17,42500,1,1,4595,...,2815,0,21,0,0,20.529997,1936,9.890562e+06,3.110509e+10,9.782322e+13
3,30,0,4,0.000000,0.000000,12,42500,1,1,3211,...,3786,0,12,0,12,9.619998,900,8.393641e+06,2.431787e+10,7.045321e+13
4,64,0,5,0.000000,0.000000,14,2500,1,1,4052,...,2580,0,44,0,33,2.750000,4096,1.090241e+07,3.599844e+10,1.188625e+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
701,45,0,702,0.182331,0.030075,12,5500,1,0,5069,...,2026,0,27,0,18,NaN,2025,1.022304e+07,3.268662e+10,1.045105e+14
702,34,0,703,0.182331,0.030075,10,2500,0,0,5885,...,465,210,18,0,4,NaN,1156,1.263040e+07,4.488754e+10,1.595271e+14
703,37,0,704,0.182331,0.030075,12,3500,1,0,4719,...,1851,0,19,0,17,NaN,1369,1.064182e+07,3.471554e+10,1.132483e+14
704,54,0,705,0.182331,0.030075,17,32500,1,0,5149,...,1481,480,31,0,22,NaN,2916,1.139586e+07,3.846988e+10,1.298657e+14
705,30,0,706,0.182331,0.030075,16,6750,1,0,4747,...,2363,0,8,1,9,NaN,900,1.062729e+07,3.464445e+10,1.129393e+14

In [5]:
model2 = smf.ols(data=df, formula='sleep~totwrk+south+totwrk*south+age+age*age+male+smsa+slp2+slp3+slp4').fit()
model2.params

Intercept      -1.093371e-02
totwrk         -2.267207e-02
south           2.984263e+01
totwrk:south   -9.116778e-03
age             5.357059e-01
male            9.495589e+00
smsa           -6.819155e+00
slp2            6.123854e-04
slp3           -7.861213e-08
slp4           -4.333186e-12
dtype: float64

In [6]:
R2=model2.rsquared
R2_res = model.rsquared

In [8]:
F_obs=((R2 - R2_res)/(1-R2))*((len(df)-12)/3)
F_obs

0.5304593589112824

In [9]:
alpha = 0.05
stats.f.ppf(1-alpha,3,len(df)-12).round(2)

2.62

$$
F_{obs}<F_{cr} \Rightarrow
$$
H0 Ð½Ðµ Ð¾Ñ‚Ð²ÐµÑ€Ð³Ð°ÐµÐ¼