In [1]:
import pandas as pd
import numpy as np
import statsmodels.formula.api as smf
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as stats

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/artamonoff/Econometrica/master/python-notebooks/data-csv/icecream.csv')
df

    obs   cons  price  income  temp  week
0     1  0.386  0.270      78    41     1
1     2  0.374  0.282      79    56     2
2     3  0.393  0.277      81    63     3
3     4  0.425  0.280      80    68     4
4     5  0.406  0.272      76    69     5
5     6  0.344  0.262      78    65     6
6     7  0.327  0.275      82    61     7
7     8  0.288  0.267      79    47     8
8     9  0.269  0.265      76    32     9
9    10  0.256  0.277      79    24    10
10   11  0.286  0.282      82    28    11
11   12  0.298  0.270      85    26    12
12   13  0.329  0.272      86    32    13
13   14  0.318  0.287      83    40    14
14   15  0.381  0.277      84    55    15
15   16  0.381  0.287      82    63    16
16   17  0.470  0.280      80    72    17
17   18  0.443  0.277      78    72    18
18   19  0.386  0.277      84    67    19
19   20  0.342  0.277      86    60    20
20   21  0.319  0.292      85    44    21
21   22  0.307  0.287      87    40    22
22   23  0.284  0.277      94    32    23
23   24  0.326  0.285      92    27    24
24   25  0.309  0.282      95    28    25
25   26  0.359  0.265      96    33    26
26   27  0.376  0.265      94    41    27
27   28  0.416  0.265      96    52    28
28   29  0.437  0.268      91    64    29
29   30  0.548  0.260      90    71    30

In [3]:
model = smf.ols(data=df, formula='cons~income+price+temp').fit(cov_type='HC3')
model.params.round

<bound method Series.round of Intercept    0.197315
income       0.003308
price       -1.044413
temp         0.003458
dtype: float64>

In [4]:
model.summary().tables[1]

In [5]:
Hi2 = stats.chi2.ppf(1-0.01,3)
Hi2

11.344866730144373

In [7]:
F_cr = stats.t.ppf(1-0.01/2,3)
F_cr.round(2)

5.84

$$
F_{cr} = 5.58
$$
$$
int = 0.62
$$
$$
income = 2.57
$$
$$
temp = 6.86
$$

## Вывод 
Значим только коэффициент temp